cat > /opt/iMouseGuard/config/rules.yaml <<'YAML'
ws_url: "ws://127.0.0.1:9000"

telegram:
  chat_id: "7365803204"
  thread_id: ""   # leave empty unless you use a Telegram topic

monitors:
  "21":
    name: "H* (Monitor 21)"
    zones:
      litter:
        keyword: "LitterBox"
        max_inactive_minutes: 60
      drink:
        keyword: "WaterBottle"
        max_inactive_minutes: 45

suppress_minutes: 30
quiet_hours:
  enable: false
  start: "22:00"
  end: "07:00"
YAML
